
# Clock signal 
set_property PACKAGE_PIN W5 [get_ports clk]  	 	 	 	  
 	set_property IOSTANDARD LVCMOS33 [get_ports clk] 
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk] 

# Switches 
set_property PACKAGE_PIN V17 [get_ports {data[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}] 
set_property PACKAGE_PIN V16 [get_ports {data[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}] 
set_property PACKAGE_PIN W16 [get_ports {data[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}] 
set_property PACKAGE_PIN W17 [get_ports {data[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}] 
set_property PACKAGE_PIN W15 [get_ports {data[4]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}] 
set_property PACKAGE_PIN V15 [get_ports {data[5]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}] 
set_property PACKAGE_PIN W14 [get_ports {data[6]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}] 
set_property PACKAGE_PIN W13 [get_ports {data[7]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}] 
set_property PACKAGE_PIN R2 [get_ports {transfer_mode}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {transfer_mode}]  
  
# LEDs 
set_property PACKAGE_PIN U16 [get_ports {buffers[0]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[0]}] 
set_property PACKAGE_PIN E19 [get_ports {buffers[1]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[1]}] 
set_property PACKAGE_PIN U19 [get_ports {buffers[2]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[2]}] 
set_property PACKAGE_PIN V19 [get_ports {buffers[3]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[3]}] 
set_property PACKAGE_PIN W18 [get_ports {buffers[4]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[4]}] 
set_property PACKAGE_PIN U15 [get_ports {buffers[5]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[5]}] 
set_property PACKAGE_PIN U14 [get_ports {buffers[6]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[6]}] 
set_property PACKAGE_PIN V14 [get_ports {buffers[7]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[7]}] 
set_property PACKAGE_PIN V13 [get_ports {buffers[8]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[8]}] 
set_property PACKAGE_PIN V3 [get_ports {buffers[9]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[9]}] 
set_property PACKAGE_PIN W3 [get_ports {buffers[10]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[10]}] 
set_property PACKAGE_PIN U3 [get_ports {buffers[11]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[11]}] 
set_property PACKAGE_PIN P3 [get_ports {buffers[12]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[12]}] 
set_property PACKAGE_PIN N3 [get_ports {buffers[13]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[13]}] 
set_property PACKAGE_PIN P1 [get_ports {buffers[14]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[14]}] 
set_property PACKAGE_PIN L1 [get_ports {buffers[15]}] 
	set_property IOSTANDARD LVCMOS33 [get_ports {buffers[15]}]
	
#7 segment display 
set_property PACKAGE_PIN W7 [get_ports {seg[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}] 
set_property PACKAGE_PIN W6 [get_ports {seg[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}] 
set_property PACKAGE_PIN U8 [get_ports {seg[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}] 
set_property PACKAGE_PIN V8 [get_ports {seg[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}] 
set_property PACKAGE_PIN U5 [get_ports {seg[4]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}] 
set_property PACKAGE_PIN V5 [get_ports {seg[5]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}] 
set_property PACKAGE_PIN U7 [get_ports {seg[6]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}] 
set_property PACKAGE_PIN U2 [get_ports {an[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}] 
set_property PACKAGE_PIN U4 [get_ports {an[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}] 
set_property PACKAGE_PIN V4 [get_ports {an[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}] 
set_property PACKAGE_PIN W4 [get_ports {an[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}] 
	
#Buttons 
set_property PACKAGE_PIN U18 [get_ports send]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports send]  
set_property PACKAGE_PIN T18 [get_ports switch_memory]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports switch_memory] 
set_property PACKAGE_PIN W19 [get_ports left]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports left] 
set_property PACKAGE_PIN T17 [get_ports right]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports right] 
set_property PACKAGE_PIN U17 [get_ports load]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports load]
 	
##Pmod Header JB 
##Sch name = JB1 
#set_property PACKAGE_PIN A14 [get_ports {TX}]  	 	 	 	 
 	#set_property IOSTANDARD LVCMOS33 [get_ports {TX}] 
##Sch name = JB2 
##set_property PACKAGE_PIN A16 [get_ports {RX}]  	 	 	 	 
 	#set_property IOSTANDARD LVCMOS33 [get_ports {RX}] 
##Sch name = JB3 
#set_property PACKAGE_PIN B15 [get_ports {JB[2]}]  	 	 	 	 
 	#set_property IOSTANDARD LVCMOS33 [get_ports {JB[2]}] ##Sch name = JB4 
#set_property PACKAGE_PIN B16 [get_ports {JB[3]}]  	 	 	 	 
 	#set_property IOSTANDARD LVCMOS33 [get_ports {JB[3]}] 
##Sch name = JB7 
#set_property PACKAGE_PIN A15 [get_ports {JB[4]}]  	 	 	 	 
 	#set_property IOSTANDARD LVCMOS33 [get_ports {JB[4]}] 
##Sch name = JB8 
#set_property PACKAGE_PIN A17 [get_ports {JB[5]}]  	 	 	 	 
 	#set_property IOSTANDARD LVCMOS33 [get_ports {JB[5]}] 
##Sch name = JB9 
#set_property PACKAGE_PIN C15 [get_ports {JB[6]}]  	 	 	 	 
 	#set_property IOSTANDARD LVCMOS33 [get_ports {JB[6]}] 
##Sch name = JB10  
#set_property PACKAGE_PIN C16 [get_ports {JB[7]}]  	 	 	 	 
 	#set_property IOSTANDARD LVCMOS33 [get_ports {JB[7]}] 